/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ReserveRouteImport } from "./routes/reserve"
import { Route as MenuRouteImport } from "./routes/menu"
import { Route as LanguageRouteImport } from "./routes/language"
import { Route as ContactsRouteImport } from "./routes/contacts"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as OrderIndexRouteImport } from "./routes/order.index"
import { Route as OrderSuccessRouteImport } from "./routes/order.success"

const ReserveRoute = ReserveRouteImport.update({
  id: "/reserve",
  path: "/reserve",
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: "/language",
  path: "/language",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: "/contacts",
  path: "/contacts",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: "/order/",
  path: "/order/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: "/order/success",
  path: "/order/success",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/contacts": typeof ContactsRoute
  "/language": typeof LanguageRoute
  "/menu": typeof MenuRoute
  "/reserve": typeof ReserveRoute
  "/order/success": typeof OrderSuccessRoute
  "/order/": typeof OrderIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/contacts": typeof ContactsRoute
  "/language": typeof LanguageRoute
  "/menu": typeof MenuRoute
  "/reserve": typeof ReserveRoute
  "/order/success": typeof OrderSuccessRoute
  "/order": typeof OrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/contacts": typeof ContactsRoute
  "/language": typeof LanguageRoute
  "/menu": typeof MenuRoute
  "/reserve": typeof ReserveRoute
  "/order/success": typeof OrderSuccessRoute
  "/order/": typeof OrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/contacts"
    | "/language"
    | "/menu"
    | "/reserve"
    | "/order/success"
    | "/order/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/contacts"
    | "/language"
    | "/menu"
    | "/reserve"
    | "/order/success"
    | "/order"
  id:
    | "__root__"
    | "/"
    | "/contacts"
    | "/language"
    | "/menu"
    | "/reserve"
    | "/order/success"
    | "/order/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  LanguageRoute: typeof LanguageRoute
  MenuRoute: typeof MenuRoute
  ReserveRoute: typeof ReserveRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/reserve": {
      id: "/reserve"
      path: "/reserve"
      fullPath: "/reserve"
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/menu": {
      id: "/menu"
      path: "/menu"
      fullPath: "/menu"
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/language": {
      id: "/language"
      path: "/language"
      fullPath: "/language"
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contacts": {
      id: "/contacts"
      path: "/contacts"
      fullPath: "/contacts"
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/order/": {
      id: "/order/"
      path: "/order"
      fullPath: "/order/"
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/order/success": {
      id: "/order/success"
      path: "/order/success"
      fullPath: "/order/success"
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  LanguageRoute: LanguageRoute,
  MenuRoute: MenuRoute,
  ReserveRoute: ReserveRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
